# Generated by Django 4.2.4 on 2023-09-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_unfinishedtesting_delete_studentsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unfinishedtesting',
            options={'verbose_name': 'Незавершённое тестирование', 'verbose_name_plural': 'Незавершённые тестирования'},
        ),
        migrations.RemoveField(
            model_name='unfinishedtesting',
            name='testings',
        ),
        migrations.AddField(
            model_name='unfinishedtesting',
            name='tasks',
            field=models.JSONField(default=1, verbose_name='Задачи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unfinishedtesting',
            name='title',
            field=models.CharField(default=2, max_length=50, unique=True, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
