# Generated by Django 4.1.4 on 2023-01-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Шаблон кода',
                'verbose_name_plural': 'Шаблоны кодов',
            },
        ),
        migrations.CreateModel(
            name='CompletedTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(verbose_name='Результат теста')),
            ],
            options={
                'verbose_name': 'Завершённое тестирование',
                'verbose_name_plural': 'Завершённые тестирования',
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Цикл')),
            ],
            options={
                'verbose_name': 'Цикл',
                'verbose_name_plural': 'Циклы',
            },
        ),
        migrations.CreateModel(
            name='OperatorNesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Вложенность операторов')),
            ],
            options={
                'verbose_name': 'Вложенность оператора',
                'verbose_name_plural': 'Вложенность операторов',
            },
        ),
        migrations.CreateModel(
            name='TaskSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('is_if_operator', models.CharField(choices=[('Присутствует', 'Присутствует'), ('Отсутствует', 'Отсутствует')], default='Отсутствует', max_length=25, verbose_name='Наличие оператора if')),
                ('condition_of_if_operator', models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], default=None, max_length=25, null=True, verbose_name='Условие оператора if')),
                ('cycle_condition', models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], default=None, max_length=25, null=True, verbose_name='Условие цикла')),
            ],
            options={
                'verbose_name': 'Настройка задачи',
                'verbose_name_plural': 'Настройки задач',
            },
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Наименование')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.tasksetting', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Тестирование',
                'verbose_name_plural': 'Тестирования',
            },
        ),
    ]
