# Generated by Django 4.1.4 on 2023-07-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='condition_of_if_operator',
            field=models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], max_length=50, null=True, verbose_name='Условие оператора if'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='cycle_condition',
            field=models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], max_length=50, null=True, verbose_name='Условие цикла'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='is_if_operator',
            field=models.CharField(choices=[('Присутствует', 'Присутствует'), ('Отсутствует', 'Отсутствует')], default='Отсутствует', max_length=50, verbose_name='Наличие оператора if'),
        ),
    ]
