# Generated by Django 4.1.4 on 2023-01-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.tasksetting', verbose_name='Настройки'),
        ),
    ]
