# Generated by Django 4.1.4 on 2023-07-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_setting_condition_of_if_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtesting',
            name='end_passage',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Окончание прохождения'),
        ),
    ]
