# Generated by Django 4.1.4 on 2023-07-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_completedtesting_end_passage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtesting',
            name='start_passage',
            field=models.DateTimeField(verbose_name='Начало прохождения'),
        ),
    ]
