# Generated by Django 4.1.4 on 2023-01-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_testing_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='title',
            field=models.CharField(max_length=25, unique=True, verbose_name='Наименование'),
        ),
    ]
