# Generated by Django 4.1.4 on 2023-01-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_alter_testing_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codetemplate',
            old_name='setting',
            new_name='task_setting',
        ),
        migrations.RenameField(
            model_name='testing',
            old_name='setting',
            new_name='task_setting',
        ),
    ]
