# Generated by Django 4.1.4 on 2023-01-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_rename_setting_codetemplate_task_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Наименование'),
        ),
    ]
