# Generated by Django 4.1.4 on 2023-07-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_testing_is_review_of_result_by_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtesting',
            name='testing',
        ),
    ]
