# Generated by Django 4.1.4 on 2023-01-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_alter_testing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='testing',
            name='id_of_one_test',
            field=models.IntegerField(default=17, verbose_name='id одного теста'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasksetting',
            name='condition_of_if_operator',
            field=models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], default='Простое', max_length=25, null=True, verbose_name='Условие оператора if'),
        ),
        migrations.AlterField(
            model_name='tasksetting',
            name='cycle_condition',
            field=models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], default='Простое', max_length=25, null=True, verbose_name='Условие цикла'),
        ),
        migrations.AlterField(
            model_name='tasksetting',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Вес'),
        ),
    ]
