# Generated by Django 4.1.4 on 2023-07-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_remove_completedtesting_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtesting',
            name='testing',
            field=models.JSONField(default={'t': 't'}, verbose_name='Тестирование'),
            preserve_default=False,
        ),
    ]
