# Generated by Django 4.1.4 on 2023-07-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_completedtesting_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtesting',
            name='testing',
        ),
        migrations.AddField(
            model_name='completedtesting',
            name='is_review_of_result_by_student',
            field=models.BooleanField(blank=True, default=True, verbose_name='Просмотр результата студентом'),
        ),
        migrations.AddField(
            model_name='completedtesting',
            name='title',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
