# Generated by Django 4.1.4 on 2023-01-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_testing_id_of_one_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='id_of_one_test',
            field=models.IntegerField(blank=True, null=True, verbose_name='id одного теста'),
        ),
    ]
