# Generated by Django 4.1.4 on 2023-07-27 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_remove_completedtesting_testing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtesting',
            name='testing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.testing', verbose_name='Тестирование'),
        ),
    ]
