# Generated by Django 4.1.4 on 2023-01-21 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0008_alter_testing_id_of_one_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksetting',
            name='user',
        ),
        migrations.AddField(
            model_name='tasksetting',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
