# Generated by Django 4.1.4 on 2023-01-22 08:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0009_remove_tasksetting_user_tasksetting_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskSetting',
            new_name='TaskSetup',
        ),
        migrations.RenameField(
            model_name='codetemplate',
            old_name='task_setting',
            new_name='task_setup',
        ),
        migrations.RenameField(
            model_name='testing',
            old_name='task_setting',
            new_name='task_setup',
        ),
    ]
