# Generated by Django 4.2.4 on 2023-08-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_alter_testing_student_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtesting',
            name='testing',
        ),
    ]
