# Generated by Django 4.1.4 on 2023-01-23 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_rename_tasksetting_tasksetup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='id_of_one_test',
        ),
        migrations.RemoveField(
            model_name='testing',
            name='task_setup',
        ),
        migrations.AddField(
            model_name='testing',
            name='is_publisher',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('task_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.tasksetup', verbose_name='Настройка задачи')),
                ('testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testing', verbose_name='Тестирование')),
            ],
        ),
    ]
