# Generated by Django 4.1.4 on 2023-01-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_remove_testing_id_of_one_test_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RenameField(
            model_name='testing',
            old_name='is_publisher',
            new_name='is_published',
        ),
    ]
