# Generated by Django 4.2.4 on 2023-08-24 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_remove_completedtesting_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtesting',
            name='testing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.testing', verbose_name='Тестирование'),
        ),
    ]
