# Generated by Django 4.1.4 on 2023-02-02 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0015_alter_completedtesting_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testing',
            old_name='student_group',
            new_name='student_groups',
        ),
        migrations.RemoveField(
            model_name='tasksetup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tasksetup',
            name='weight',
        ),
        migrations.AddField(
            model_name='codetemplate',
            name='is_use',
            field=models.BooleanField(default=1, verbose_name='Использовался'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='weight',
            field=models.IntegerField(default=1, verbose_name='Вес'),
        ),
        migrations.AddField(
            model_name='tasksetup',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
