# Generated by Django 4.1.4 on 2023-02-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0016_rename_student_group_testing_student_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Опубликовано'),
        ),
    ]
