# Generated by Django 4.1.4 on 2023-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0017_alter_testing_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, verbose_name='Опубликовано'),
        ),
    ]
