# Generated by Django 4.1.4 on 2023-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0018_alter_testing_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksetup',
            name='cycle_condition',
            field=models.BooleanField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], default='Простое', null=True, verbose_name='Условие цикла'),
        ),
        migrations.AlterField(
            model_name='tasksetup',
            name='is_if_operator',
            field=models.BooleanField(choices=[('True', 'Присутствует'), ('False', 'Отсутствует')], default='False', verbose_name='Наличие оператора if'),
        ),
    ]
