# Generated by Django 4.1.4 on 2023-02-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0019_alter_tasksetup_cycle_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksetup',
            name='cycle_condition',
            field=models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], default='Простое', max_length=25, null=True, verbose_name='Условие цикла'),
        ),
        migrations.AlterField(
            model_name='tasksetup',
            name='is_if_operator',
            field=models.BooleanField(choices=[('Присутствует', 'Присутствует'), ('Отсутствует', 'Отсутствует')], default='Отсутствует', verbose_name='Наличие оператора if'),
        ),
    ]
