# Generated by Django 4.1.4 on 2023-02-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0021_alter_tasksetup_is_if_operator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksetup',
            old_name='presence_one_of_following_cycles',
            new_name='presence_one_of_cycles',
        ),
    ]
