# Generated by Django 4.1.4 on 2023-02-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0022_rename_presence_one_of_following_cycles_tasksetup_presence_one_of_cycles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksetup',
            name='operator_nesting',
            field=models.ManyToManyField(blank=True, null=True, to='testing.operatornesting', verbose_name='Вложенность операторов'),
        ),
        migrations.AlterField(
            model_name='tasksetup',
            name='presence_one_of_cycles',
            field=models.ManyToManyField(blank=True, null=True, to='testing.cycle', verbose_name='Наличие одного из следующих циклов'),
        ),
    ]
