# Generated by Django 4.1.4 on 2023-02-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0024_alter_tasksetup_cycle_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksetup',
            name='cycle_condition',
            field=models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], default='Простое', max_length=25, null=True, verbose_name='Условие цикла'),
        ),
    ]
