# Generated by Django 4.1.4 on 2023-02-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0026_alter_tasksetup_cycle_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksetup',
            name='condition_of_if_operator',
            field=models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], max_length=25, null=True, verbose_name='Условие оператора if'),
        ),
    ]
