# Generated by Django 4.1.4 on 2023-03-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0028_remove_completedtesting_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtesting',
            name='student_scores',
        ),
        migrations.RemoveField(
            model_name='completedtesting',
            name='total_scores',
        ),
        migrations.AddField(
            model_name='completedtesting',
            name='total_weight',
            field=models.IntegerField(default=1, verbose_name='Общий вес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedtesting',
            name='weight_of_student_tasks',
            field=models.IntegerField(default=1, verbose_name='Вес задач студента'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasksetup',
            name='use_of_all_variables',
            field=models.BooleanField(default=False, verbose_name='Использование обязательно всех переменных'),
        ),
    ]
