# Generated by Django 4.1.4 on 2023-03-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0029_remove_completedtesting_student_scores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksetup',
            name='use_of_all_variables',
        ),
    ]
