# Generated by Django 4.1.4 on 2023-05-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0031_alter_completedtesting_testing_alter_testing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksetup',
            name='is_OOP',
            field=models.BooleanField(default=False, verbose_name='ООП'),
        ),
    ]
