# Generated by Django 4.1.4 on 2023-05-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0032_tasksetup_is_oop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksetup',
            name='is_strings',
            field=models.BooleanField(default=False, verbose_name='Строки'),
        ),
    ]
