# Generated by Django 4.2.4 on 2023-10-08 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_unfinishedtesting_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing_by_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtesting',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='student_groups',
            field=models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_related', to='user.studentgroup', verbose_name='Группы студентов'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
