# Generated by Django 4.2.4 on 2024-06-12 15:20

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('testing_by_code', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='users',
        ),
        migrations.RemoveField(
            model_name='solvingtesting',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='solvingtesting',
            name='title',
        ),
        migrations.RemoveField(
            model_name='solvingtesting',
            name='total_weight',
        ),
        migrations.RemoveField(
            model_name='solvingtesting',
            name='weight_of_student_tasks',
        ),
        migrations.RemoveField(
            model_name='testing',
            name='user',
        ),
        migrations.AddField(
            model_name='solvingtesting',
            name='earned_weight',
            field=models.IntegerField(null=True, verbose_name='Заработанный вес'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='lead_time',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Время выполнения'),
        ),
        migrations.AddField(
            model_name='task',
            name='serial_number',
            field=models.IntegerField(blank=True, default=1, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testing',
            name='is_established_order_tasks',
            field=models.BooleanField(default=False, verbose_name='Установленный порядок задач'),
        ),
        migrations.AddField(
            model_name='testing',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='user.teacher', verbose_name='Преподаватель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='is_if_operator',
            field=models.BooleanField(default=False, verbose_name='Наличие оператора if'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='total_weight',
            field=models.IntegerField(verbose_name='Общий вес'),
        ),
        migrations.CreateModel(
            name='SolvingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=100, verbose_name='Ответ')),
                ('start_passage', models.DateTimeField(blank=True, null=True, verbose_name='Начало прохождения')),
                ('lead_time', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('code', models.TextField(verbose_name='Код')),
                ('correct_answer', models.CharField(max_length=100, verbose_name='Правильный ответ')),
                ('solving_testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_by_code.solvingtesting', verbose_name='Тестирование')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_by_code.task', verbose_name='Задача')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
