# Generated by Django 4.2.4 on 2024-03-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_by_code', '0002_alter_completedtesting_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtesting',
            name='assessment',
            field=models.IntegerField(null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='completedtesting',
            name='start_passage',
            field=models.DateTimeField(null=True, verbose_name='Начало прохождения'),
        ),
        migrations.AlterField(
            model_name='completedtesting',
            name='title',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Наименование'),
        ),
    ]
