# Generated by Django 4.2.4 on 2024-06-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_by_code', '0002_remove_setting_users_remove_solvingtesting_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='total_weight',
            field=models.IntegerField(default=0, verbose_name='Общий вес'),
        ),
    ]
