# Generated by Django 4.2.4 on 2024-06-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing_by_code', '0004_alter_task_count_alter_task_setting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvingtask',
            name='solving_testing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solving_task_set', to='testing_by_code.solvingtesting', verbose_name='Тестирование'),
        ),
        migrations.AlterField(
            model_name='solvingtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solving_task_set', to='testing_by_code.task', verbose_name='Задача'),
        ),
    ]
