# Generated by Django 4.2.4 on 2024-06-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_by_code', '0005_alter_solvingtask_solving_testing_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='solvingtask',
            table='testing_by_code_solving-task',
        ),
    ]
