# Generated by Django 4.2.4 on 2024-06-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_by_code', '0006_alter_solvingtask_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='operatornesting',
            table='testing_by_code_operator_nesting',
        ),
        migrations.AlterModelTable(
            name='solvingtesting',
            table='testing_by_code_solving-testing',
        ),
    ]
