# Generated by Django 4.2.4 on 2024-06-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_by_code', '0007_alter_operatornesting_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvingtask',
            name='is_correctly_resolved',
            field=models.BooleanField(default=False, verbose_name='Правильно решена'),
            preserve_default=False,
        ),
    ]
