# Generated by Django 4.2.4 on 2024-06-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_by_code', '0008_solvingtask_is_correctly_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solvingtask',
            name='is_correctly_resolved',
        ),
    ]
