# Generated by Django 4.2.4 on 2024-06-17 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_by_code', '0009_remove_solvingtask_is_correctly_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='total_weight',
        ),
    ]
