# Generated by Django 4.2.4 on 2024-08-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_by_code', '0010_remove_testing_total_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solvingtask',
            options={'ordering': ['task__serial_number']},
        ),
        migrations.AddField(
            model_name='solvingtesting',
            name='duration',
            field=models.DurationField(null=True, verbose_name='Длительность теста'),
        ),
    ]
