# Generated by Django 4.2.4 on 2024-08-26 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testing_by_code', '0011_alter_solvingtask_options_solvingtesting_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvingtesting',
            name='start_passage',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало прохождения'),
        ),
    ]
