# Generated by Django 4.2.4 on 2024-08-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_by_code', '0013_remove_solvingtesting_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvingtesting',
            name='start_passage',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Начало прохождения'),
        ),
    ]
