# Generated by Django 4.2.4 on 2025-01-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_user_schedule_teacher'),
        ('base_testing', '0002_alter_maxscore_table'),
        ('testing_by_code', '0014_alter_solvingtesting_start_passage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='student_groups',
        ),
        migrations.RemoveField(
            model_name='testing',
            name='teacher',
        ),
        migrations.AddField(
            model_name='solvingtask',
            name='end_passage',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец прохождения'),
        ),
        migrations.AddField(
            model_name='testing',
            name='max_score',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='base_testing.maxscore', verbose_name='Максимальный балл'),
        ),
        migrations.AddField(
            model_name='testing',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='user.schedule', verbose_name='Журнал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testing',
            name='total_weight',
            field=models.IntegerField(default=0, verbose_name='Общий вес'),
        ),
    ]
