# Generated by Django 4.2.4 on 2025-07-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_by_code', '0016_rename_schedule_testing_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvingtask',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ'),
        ),
    ]
