# Generated by Django 4.2.4 on 2025-07-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_by_code', '0017_alter_solvingtask_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='count',
        ),
    ]
