# Generated by Django 4.2.4 on 2025-07-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_by_code', '0018_remove_task_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['serial_number'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
