# Generated by Django 4.1.4 on 2023-01-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(verbose_name='Результат теста')),
            ],
        ),
        migrations.CreateModel(
            name='TaskSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('is_if_statement', models.BooleanField(choices=[('True', 'Присутствует'), ('False', 'Отсутствует')], default='False', max_length=5, verbose_name='Наличие оператора if')),
                ('condition_of_if_statement', models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], default='Простое', max_length=25, verbose_name='Условие оператора if')),
                ('availability_of_cycles', models.CharField(blank=True, choices=[('while', 'while'), ('do-while', 'do-while'), ('for', 'for')], max_length=25, verbose_name='Наличие одного из следующих циклов')),
                ('cycle_condition', models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], default='Простое', max_length=25, verbose_name='Условие оператора if')),
                ('operator_nesting', models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], max_length=25, verbose_name='Условие оператора if')),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Наименование')),
                ('setting', models.ManyToManyField(to='testing.tasksetting')),
            ],
        ),
    ]
