# Generated by Django 4.1.4 on 2023-01-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codetemplate',
            options={'verbose_name': 'Шаблон кода', 'verbose_name_plural': 'Шаблоны кодов'},
        ),
        migrations.AlterModelOptions(
            name='completedtesting',
            options={'verbose_name': 'Завершённое тестирование', 'verbose_name_plural': 'Завершённые тестирования'},
        ),
        migrations.AlterModelOptions(
            name='tasksetting',
            options={'verbose_name': 'Настройка задачи', 'verbose_name_plural': 'Настройки задач'},
        ),
        migrations.AlterModelOptions(
            name='testing',
            options={'verbose_name': 'Тестирование', 'verbose_name_plural': 'Тестирования'},
        ),
    ]
