# Generated by Django 4.1.4 on 2023-01-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_codetemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksetting',
            name='is_if_statement',
            field=models.CharField(choices=[('Присутствует', 'Присутствует'), ('Отсутствует', 'Отсутствует')], default='Отсутствует', max_length=25, verbose_name='Наличие оператора if'),
        ),
    ]
