# Generated by Django 4.1.4 on 2023-01-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_alter_tasksetting_is_if_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksetting',
            name='condition_of_if_statement',
            field=models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], max_length=25, verbose_name='Условие оператора if'),
        ),
        migrations.AlterField(
            model_name='tasksetting',
            name='cycle_condition',
            field=models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], max_length=25, verbose_name='Условие цикла'),
        ),
        migrations.AlterField(
            model_name='tasksetting',
            name='operator_nesting',
            field=models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], max_length=25, verbose_name='Вложенность операторов'),
        ),
    ]
