# Generated by Django 4.1.4 on 2023-01-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_alter_tasksetting_condition_of_if_statement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Цикл')),
            ],
        ),
        migrations.RemoveField(
            model_name='tasksetting',
            name='availability_of_cycles',
        ),
        migrations.AlterField(
            model_name='tasksetting',
            name='is_if_statement',
            field=models.CharField(choices=[('attend', 'Присутствует'), ('Отсутствует', 'Отсутствует')], default='Отсутствует', max_length=25, verbose_name='Наличие оператора if'),
        ),
        migrations.AddField(
            model_name='tasksetting',
            name='availability_of_cycles',
            field=models.ManyToManyField(to='testing.cycle'),
        ),
    ]
