# Generated by Django 4.1.4 on 2023-01-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_cycle_remove_tasksetting_availability_of_cycles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorNesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Вложенность операторов')),
            ],
            options={
                'verbose_name': 'Вложенность оператора',
                'verbose_name_plural': 'Вложенность операторов',
            },
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'verbose_name': 'Цикл', 'verbose_name_plural': 'Циклы'},
        ),
        migrations.AlterField(
            model_name='tasksetting',
            name='availability_of_cycles',
            field=models.ManyToManyField(to='testing.cycle', verbose_name='Наличие цикла'),
        ),
        migrations.RemoveField(
            model_name='tasksetting',
            name='operator_nesting',
        ),
        migrations.AddField(
            model_name='tasksetting',
            name='operator_nesting',
            field=models.ManyToManyField(to='testing.operatornesting', verbose_name='Вложенность операторов'),
        ),
    ]
