# Generated by Django 4.1.4 on 2023-01-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_operatornesting_alter_cycle_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksetting',
            name='availability_of_cycles',
            field=models.ManyToManyField(blank=True, to='testing.cycle', verbose_name='Наличие цикла'),
        ),
        migrations.AlterField(
            model_name='tasksetting',
            name='condition_of_if_statement',
            field=models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], default=None, max_length=25, null=True, verbose_name='Условие оператора if'),
        ),
        migrations.AlterField(
            model_name='tasksetting',
            name='cycle_condition',
            field=models.CharField(blank=True, choices=[('Простое', 'Простое'), ('Составное', 'Составное')], default=None, max_length=25, null=True, verbose_name='Условие цикла'),
        ),
        migrations.AlterField(
            model_name='tasksetting',
            name='is_if_statement',
            field=models.CharField(choices=[('Присутствует', 'Присутствует'), ('Отсутствует', 'Отсутствует')], default='Отсутствует', max_length=25, verbose_name='Наличие оператора if'),
        ),
        migrations.AlterField(
            model_name='tasksetting',
            name='operator_nesting',
            field=models.ManyToManyField(blank=True, to='testing.operatornesting', verbose_name='Вложенность операторов'),
        ),
    ]
