# Generated by Django 4.1.4 on 2023-01-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_alter_tasksetting_availability_of_cycles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksetting',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codetemplate',
            name='setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.tasksetting', verbose_name='Настройка'),
        ),
    ]
