# Generated by Django 4.1.4 on 2023-01-04 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_group_studentgroup_remove_user_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0009_tasksetting_title_alter_codetemplate_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksetting',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testing',
            name='student_group',
            field=models.ManyToManyField(to='user.studentgroup'),
        ),
        migrations.AddField(
            model_name='testing',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
