# Generated by Django 4.1.4 on 2023-01-06 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_rename_group_studentgroup_remove_user_group_and_more'),
        ('testing', '0010_tasksetting_user_testing_student_group_testing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksetting',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='setting',
            field=models.ManyToManyField(to='testing.tasksetting', verbose_name='Настройки'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='student_group',
            field=models.ManyToManyField(to='user.studentgroup', verbose_name='Группы студентов'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
