# Generated by Django 4.1.4 on 2023-01-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0012_rename_is_if_statement_tasksetting_is_if_operator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksetting',
            old_name='condition_of_if_statement',
            new_name='condition_of_if_operator',
        ),
    ]
