# Generated by Django 4.1.4 on 2023-01-08 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0013_rename_condition_of_if_statement_tasksetting_condition_of_if_operator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='setting',
        ),
        migrations.AddField(
            model_name='testing',
            name='setting',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='testing.tasksetting', verbose_name='Настройки'),
            preserve_default=False,
        ),
    ]
