# Generated by Django 4.1.4 on 2023-01-08 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0014_remove_testing_setting_testing_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksetting',
            name='title',
        ),
    ]
