# Generated by Django 4.1.4 on 2023-01-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0015_remove_tasksetting_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='setting',
        ),
        migrations.AddField(
            model_name='tasksetting',
            name='testing',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='testing.testing', verbose_name='Тестирование'),
            preserve_default=False,
        ),
    ]
