# Generated by Django 4.2.4 on 2025-01-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maxscore',
            table='base-testing_max-score',
        ),
    ]
