from .abstract_form_set_view import AbstractFormSetView
from .abstract_task_create_view import AbstractTaskCreateView
from .abstract_task_detail_view import AbstractTaskDetailView
from .abstract_task_update_view import AbstractTaskUpdateView
from .abstract_task_delete_view import AbstractTaskDeleteView
