from .abstract_task_view import AbstractTaskView
from .abstract_form_set_view import AbstractFormSetView
from .abstract_task_create_or_update_view import AbstractTaskCreateOrUpdateView
from .abstract_task_create_view import AbstractTaskCreateView
from .abstract_task_detail_view import AbstractTaskDetailView
from .abstract_task_update_view import AbstractTaskUpdateView
from .abstract_task_with_choice_create_or_update_view import AbstractTaskWithChoiceCreateOrUpdateView
from .abstract_closed_question_create_or_update_view import AbstractClosedQuestionCreateOrUpdateView
