from .testing_create_view import TestingCreateView
from .teacher_testing_detail_view import TeacherTestingDetailView
from .student_solving_testing_detail_view import StudentSolvingTestingDetailView
from .testing_update_view import TestingUpdateView
from .testing_delete_view import TestingDeleteView
