from .testing_create_view import TestingCreateView
from .testing_detail_teacher_view import TestingDetailTeacherView
from .testing_detail_student_view import TestingDetailStudentView
from .testing_update_view import TestingUpdateView
from .testing_delete_view import TestingDeleteView
from .testing_list_view import TestingListView
