# Generated by Django 4.2.4 on 2023-10-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testing',
            options={'verbose_name': 'Тестирование', 'verbose_name_plural': 'Тестирования'},
        ),
        migrations.AlterModelTable(
            name='testing',
            table=None,
        ),
    ]
