# Generated by Django 4.2.4 on 2024-05-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closedquestion',
            options={'ordering': ['serial_number']},
        ),
        migrations.AlterModelOptions(
            name='openquestion',
            options={'ordering': ['serial_number']},
        ),
        migrations.RemoveField(
            model_name='closedquestion',
            name='testing',
        ),
        migrations.AddField(
            model_name='closedquestion',
            name='testing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='closed_question_set', to='testing.testing', verbose_name='Тестирование'),
            preserve_default=False,
        ),
    ]
