# Generated by Django 4.2.4 on 2024-05-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_closedquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedquestion',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_question_set', to='testing.tasktype', verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_question_set', to='testing.tasktype', verbose_name='Тип задачи'),
        ),
    ]
