# Generated by Django 4.2.4 on 2023-10-15 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_testing_options_alter_testing_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedquestion',
            name='testing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='testing.testing', verbose_name='Тестирование'),
            preserve_default=False,
        ),
    ]
