# Generated by Django 4.2.4 on 2024-05-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_alter_closedquestion_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solvingtesting',
            options={'verbose_name': 'Решение тестирования', 'verbose_name_plural': 'Решения тестирований'},
        ),
        migrations.RemoveField(
            model_name='solvingtesting',
            name='title',
        ),
    ]
