# Generated by Django 4.2.4 on 2023-12-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_remove_answeroption_text_remove_closedquestion_text_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='completedtesting',
            table='testing_сompletedTesting',
        ),
    ]
