# Generated by Django 4.2.4 on 2024-05-04 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('testing', '0005_alter_solvingtesting_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='user',
        ),
        migrations.AddField(
            model_name='testing',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='user.teacher', verbose_name='Преподаватель'),
            preserve_default=False,
        ),
    ]
