# Generated by Django 4.2.4 on 2024-05-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_remove_testing_user_testing_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvingclosedquestion',
            name='lead_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='solvingclosedquestion',
            name='start_passage',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало прохождения'),
        ),
        migrations.AlterField(
            model_name='solvingopenquestion',
            name='lead_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='solvingopenquestion',
            name='start_passage',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало прохождения'),
        ),
    ]
