# Generated by Django 4.2.4 on 2024-01-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_remove_testing_lead_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='photo',
            field=models.ImageField(blank=True, upload_to='%(app_label)/%(class)', verbose_name='Фото'),
        ),
    ]
