# Generated by Django 4.2.4 on 2024-01-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_answeroption_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='serial_number',
            field=models.IntegerField(blank=True, default=1, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Тестирование/Задачи/Закрытый вопрос/Варианты ответа', verbose_name='Фото'),
        ),
    ]
