# Generated by Django 4.2.4 on 2024-01-21 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_answeroption_serial_number_alter_answeroption_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedquestion',
            name='serial_number',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedquestion',
            name='type',
            field=models.CharField(default='Закрытый вопрос'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='closed_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_questions', to='testing.closedquestion', verbose_name='Закрытый вопрос'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='serial_number',
            field=models.IntegerField(verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='closedquestion',
            name='testing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testings', to='testing.testing', verbose_name='Тестирование'),
        ),
    ]
