# Generated by Django 4.2.4 on 2024-05-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_alter_solvingclosedquestion_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solvingclosedquestion',
            old_name='closed_question',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='solvingopenquestion',
            old_name='open_question',
            new_name='task',
        ),
    ]
