# Generated by Django 4.2.4 on 2024-01-21 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_closedquestion_serial_number_closedquestion_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='closed_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.closedquestion', verbose_name='Закрытый вопрос'),
        ),
        migrations.AlterField(
            model_name='closedquestion',
            name='testing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testing', verbose_name='Тестирование'),
        ),
    ]
