# Generated by Django 4.2.4 on 2024-01-21 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_alter_answeroption_closed_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='closed_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_question_related', to='testing.closedquestion', verbose_name='Закрытый вопрос'),
        ),
        migrations.AlterField(
            model_name='closedquestion',
            name='testing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_related', to='testing.testing', verbose_name='Тестирование'),
        ),
    ]
