# Generated by Django 4.2.4 on 2024-08-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_alter_solvingtesting_start_passage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solvingtesting',
            name='duration',
        ),
    ]
