# Generated by Django 4.2.4 on 2024-01-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_alter_answeroption_closed_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closedquestion',
            options={'ordering': ['serial_number']},
        ),
        migrations.AlterField(
            model_name='closedquestion',
            name='serial_number',
            field=models.IntegerField(blank=True, verbose_name='Порядковый номер'),
        ),
    ]
