# Generated by Django 4.2.4 on 2024-01-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0012_alter_closedquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='photo',
            field=models.ImageField(blank=True, upload_to='test', verbose_name='Фото'),
        ),
    ]
