# Generated by Django 4.2.4 on 2024-09-12 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0013_alter_solvingtesting_start_passage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxscore',
            name='five',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Отлично'),
        ),
        migrations.AlterField(
            model_name='maxscore',
            name='four',
            field=models.IntegerField(default=80, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Хорошо'),
        ),
        migrations.AlterField(
            model_name='maxscore',
            name='three',
            field=models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Удовлетворительно'),
        ),
        migrations.AlterField(
            model_name='maxscore',
            name='two',
            field=models.IntegerField(default=40, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Неудовлетворительно'),
        ),
    ]
