# Generated by Django 4.2.4 on 2024-01-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0013_alter_answeroption_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeroption',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Testing/Task/Closed question/Answer options', verbose_name='Фото'),
        ),
    ]
