# Generated by Django 4.2.4 on 2024-01-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0014_alter_answeroption_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerOption',
            new_name='ClosedQuestionAnswerOption',
        ),
    ]
