# Generated by Django 4.2.4 on 2024-02-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0015_rename_answeroption_closedquestionansweroption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closedquestionansweroption',
            options={'ordering': ['serial_number']},
        ),
        migrations.RemoveField(
            model_name='closedquestionansweroption',
            name='photo',
        ),
        migrations.AlterField(
            model_name='closedquestion',
            name='is_partially_correct_execution',
            field=models.BooleanField(default=False, verbose_name='При оценке учесть частично правильное выполнение задания'),
        ),
        migrations.AlterField(
            model_name='closedquestion',
            name='is_several_correct_answers',
            field=models.BooleanField(default=False, verbose_name='Допустимо несколько правильных ответов'),
        ),
    ]
