# Generated by Django 4.2.4 on 2024-09-22 13:41

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0015_sequencing_solvingsequencing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequencing',
            name='is_correct',
        ),
        migrations.CreateModel(
            name='SequencingAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(blank=True, verbose_name='Порядковый номер')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
                ('is_correct', models.BooleanField(verbose_name='Правильный')),
                ('sequencing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_question_answer_option_set', to='testing.sequencing', verbose_name='Закрытый вопрос')),
            ],
            options={
                'db_table': 'testing_sequencing-answer-option',
                'ordering': ['serial_number'],
                'abstract': False,
            },
        ),
    ]
