# Generated by Django 4.2.4 on 2024-10-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0016_remove_sequencing_is_correct_sequencingansweroption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingansweroption',
            name='sequencing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequencing_answer_option_set', to='testing.sequencing', verbose_name='Установление последовательности'),
        ),
    ]
