# Generated by Django 4.2.4 on 2024-02-04 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0016_alter_closedquestionansweroption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedquestion',
            name='testing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_question_set', to='testing.testing', verbose_name='Тестирование'),
        ),
        migrations.AlterField(
            model_name='closedquestionansweroption',
            name='closed_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_related', to='testing.closedquestion', verbose_name='Закрытый вопрос'),
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1, verbose_name='Вес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('correct_answer', models.TextField(verbose_name='Правильный ответ')),
                ('testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_question_set', to='testing.testing', verbose_name='Тестирование')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
