# Generated by Django 4.2.4 on 2024-02-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0017_alter_closedquestion_testing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedquestionansweroption',
            name='closed_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_question_answer_option_set', to='testing.closedquestion', verbose_name='Закрытый вопрос'),
        ),
        migrations.AlterField(
            model_name='maxscore',
            name='testing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='max_score_set', to='testing.testing', verbose_name='Тестирование'),
        ),
    ]
