# Generated by Django 4.2.4 on 2024-02-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0018_alter_closedquestionansweroption_closed_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openquestion',
            name='type',
            field=models.CharField(default='Открытый вопрос'),
        ),
    ]
