# Generated by Django 4.2.4 on 2024-12-22 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0018_answeroption_solvingtask_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_option_set', to='testing.task', verbose_name='Задача'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closedquestion',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='closed_question_set', to='testing.task', verbose_name='Задача'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openquestionansweroption',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='open_question_answer_option_set', to='testing.task', verbose_name='Задача'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='testing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.testing', verbose_name='Тестирование'),
            preserve_default=False,
        ),
    ]
