# Generated by Django 4.2.4 on 2024-02-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0019_openquestion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='openquestion',
            name='serial_number',
            field=models.IntegerField(blank=True, default=4, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
    ]
