# Generated by Django 4.2.4 on 2024-12-27 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0019_answeroption_task_closedquestion_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedquestion',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closed_question_set', to='testing.task', verbose_name='Задача'),
        ),
    ]
