# Generated by Django 4.2.4 on 2025-01-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0020_alter_closedquestion_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedquestion',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closed_question_set', related_query_name='additional_model', to='testing.task', verbose_name='Задача'),
        ),
    ]
