# Generated by Django 4.2.4 on 2024-02-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0021_remove_closedquestion_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenQuestionAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(verbose_name='Правильный ответ')),
                ('open_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_question_answer_option_set', to='testing.openquestion', verbose_name='Закрытый вопрос')),
            ],
            options={
                'db_table': 'testing_openQuestion_answerOption',
            },
        ),
    ]
