# Generated by Django 4.2.4 on 2024-02-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0023_alter_closedquestionansweroption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closedquestionansweroption',
            options={'ordering': ['serial_number']},
        ),
    ]
