# Generated by Django 4.2.4 on 2025-01-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0023_remove_testing_student_groups_remove_testing_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testing',
            old_name='schedule',
            new_name='journal',
        ),
    ]
