# Generated by Django 4.2.4 on 2025-02-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0024_rename_schedule_testing_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='correct_answer',
        ),
    ]
