# Generated by Django 4.2.4 on 2024-02-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0024_alter_closedquestionansweroption_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openquestion',
            options={},
        ),
    ]
