# Generated by Django 4.2.4 on 2025-03-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0025_remove_task_correct_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solvingtask',
            options={'ordering': ('task__serial_number',)},
        ),
        migrations.AlterField(
            model_name='solvingtask',
            name='answer',
            field=models.JSONField(blank=True, verbose_name='Ответ'),
        ),
    ]
