# Generated by Django 4.2.4 on 2024-02-24 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0025_alter_openquestion_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedOpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(blank=True, verbose_name='Порядковый номер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type', models.CharField(default='Открытый вопрос')),
                ('user_answer', models.TextField(verbose_name='Ответ пользователя')),
                ('completed_testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_open_question_set', to='testing.completedtesting', verbose_name='Завершённое тестирование')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompletedOpenQuestionAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(verbose_name='Правильный ответ')),
                ('completed_open_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_open_question_answer_option_set', to='testing.completedopenquestion', verbose_name='Завершённый открытый вопрос')),
            ],
            options={
                'db_table': 'testing_completedOpenQuestion_answerOption',
            },
        ),
    ]
