# Generated by Django 4.2.4 on 2024-02-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0026_completedopenquestion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='completedopenquestion',
            table='completedOpenQuestion',
        ),
    ]
