# Generated by Django 4.2.4 on 2024-02-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0027_alter_completedopenquestion_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='completedopenquestion',
            table='testing_completedOpenQuestion',
        ),
    ]
