# Generated by Django 4.2.4 on 2024-02-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0028_alter_completedopenquestion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedopenquestion',
            name='user_answer',
            field=models.CharField(verbose_name='Ответ пользователя'),
        ),
    ]
