# Generated by Django 4.2.4 on 2025-06-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0029_alter_solvingtask_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvingtask',
            name='score',
            field=models.FloatField(default=0.0, verbose_name='Балл'),
        ),
    ]
