# Generated by Django 4.2.4 on 2024-02-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0029_alter_completedopenquestion_user_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closedquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='closedquestionansweroption',
            options={},
        ),
        migrations.RemoveField(
            model_name='completedtesting',
            name='total_weight',
        ),
        migrations.RemoveField(
            model_name='completedtesting',
            name='weight_of_student_tasks',
        ),
    ]
