# Generated by Django 4.2.4 on 2024-02-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0030_alter_closedquestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedQuestionAnswerOptionStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(blank=True, verbose_name='Порядковый номер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_correct', models.BooleanField(verbose_name='Правильный')),
            ],
            options={
                'db_table': 'testing_closedQuestion_answerOption_student',
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='CompletedOpenQuestionAnswerOption',
            new_name='OpenQuestionAnswerOptionCorrect',
        ),
        migrations.RemoveField(
            model_name='completedopenquestion',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='completedopenquestion',
            name='student_answer',
            field=models.CharField(default=1, verbose_name='Ответ студента'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='openquestionansweroptioncorrect',
            table='testing_completedOpenQuestion_answerOption_correct',
        ),
        migrations.CreateModel(
            name='ClosedQuestionAnswerOptionCorrect',
            fields=[
                ('serial_number', models.IntegerField(blank=True, verbose_name='Порядковый номер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_correct', models.BooleanField(verbose_name='Правильный')),
                ('closed_question_answer_option_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='closed_question_answer_option_correct_set', serialize=False, to='testing.closedquestionansweroptionstudent', verbose_name='Закрытый вопрос вариант ответа студента')),
            ],
            options={
                'db_table': 'testing_closedQuestion_answerOption_correct',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompletedClosedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(blank=True, verbose_name='Порядковый номер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type', models.CharField(default='Закрытый вопрос')),
                ('is_several_correct_answers', models.BooleanField(default=False, verbose_name='Допустимо несколько правильных ответов')),
                ('is_random_order_answer_options', models.BooleanField(default=False, verbose_name='Случайный порядок вариантов ответа')),
                ('is_partially_correct_execution', models.BooleanField(default=False, verbose_name='При оценке учесть частично правильное выполнение задания')),
                ('completed_testing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_closed_question_set', to='testing.completedtesting', verbose_name='Завершённое тестирование')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='closedquestionansweroptionstudent',
            name='completed_closed_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_question_answer_option_student_set', to='testing.completedclosedquestion', verbose_name='Закрытый вопрос'),
        ),
    ]
