# Generated by Django 4.2.4 on 2024-03-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0034_alter_completedtesting_end_passage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtesting',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
    ]
