# Generated by Django 4.1.4 on 2023-01-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('testing', '0005_alter_tasksetting_condition_of_if_statement_and_more'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user', '0003_rename_user_customuser_alter_group_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
