# Generated by Django 4.1.4 on 2023-01-01 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_customuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='StudentGroup',
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='user',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.studentgroup', verbose_name='Группа студента'),
        ),
    ]
