# Generated by Django 4.2.4 on 2025-01-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'дисциплина',
                'verbose_name_plural': 'дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Название')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'семестр',
                'verbose_name_plural': 'семестры',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absolute_journal_name', models.CharField(blank=True, max_length=200, unique=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.discipline', verbose_name='Дисциплина')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.semester', verbose_name='Семестр')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.studentgroup', verbose_name='Группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'журнал',
                'verbose_name_plural': 'журналы',
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='semesters',
            field=models.ManyToManyField(related_name='disciplines', through='user.Schedule', to='user.semester', verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='student_groups',
            field=models.ManyToManyField(related_name='disciplines', through='user.Schedule', to='user.studentgroup', verbose_name='Группа'),
        ),
    ]
