# Generated by Django 4.1.4 on 2023-05-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
