# Generated by Django 4.2.4 on 2025-01-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0024_rename_schedule_testing_journal'),
        ('testing_by_code', '0016_rename_schedule_testing_journal'),
        ('user', '0003_rename_user_schedule_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='Journal',
        ),
    ]
