# Generated by Django 4.2.4 on 2023-09-10 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_studentsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnfinishedTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testings', models.JSONField(verbose_name='Тестирования')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentSession',
        ),
    ]
