# Generated by Django 4.2.4 on 2024-03-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_unfinishedtesting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unfinishedtesting',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
    ]
